services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
  streamlit:
    build:
      dockerfile: Dockerfile-gpu
    environment:
      HF_TOKEN: <HF API token>
    depends_on:
      - postgres
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 'all'
    working_dir: /app/llarga
    ports:
      - 8502:8502
    volumes:
      - <local corpora directory>:/app/llarga/corpora
      - <local metadata directory>:/app/llarga/metadata
      - <local models directory>:/app/llarga/models
      - <local secret.toml file path>:/app/llarga/.streamlit/secrets.toml
    command: ["streamlit", "run", "app.py", "--server.port=8502", "--server.address=0.0.0.0"]
